name: wallet
description: AXIA's native blockchain wallet with Multicurrency .

publish_to: 'none'
version: 2.0.3+30

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: any
  qr_flutter: ^4.0.0
  qr_code_scanner: 1.0.0
  persistent_bottom_nav_bar: ^4.0.2
  share_plus: ^4.0.8
  carousel_slider: ^4.0.0
  webview_flutter: any
  local_auth: any
  pinput: ^1.2.1
  intl_phone_number_input: ^0.7.0+2
  device_info_plus: ^3.2.2
  get_storage: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  google_fonts: ^2.3.1
  http: ^0.13.4
  animations: ^2.0.2
  flutter_speed_dial: ^5.0.0+1
  coinslib: ^3.1.1
  bip39: ^1.0.6
  bip32: ^2.0.0
  web3dart: ^2.3.5
  encrypt: ^5.0.1
  hex: ^0.2.0
  flutter_svg: ^1.0.3
  rename: ^2.0.1
  url_launcher: ^6.1.2
  socket_io_client: ^1.0.2
  time_picker_widget: ^1.0.0+10
  searchable_listview: ^1.6.0
  auto_size_text: ^3.0.0
  flutter_secure_storage: ^5.0.2
  axwallet_sdk:
    git: 
      url: https://github.com/AxiaCoin/axia-network-v2-axwallet-sdk.git
  package_info_plus: ^1.4.2
  flutter_inappwebview: ^5.4.3+7
  path_provider: ^2.0.11


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: any
  
dependency_overrides:
  axwallet_sdk:
    path: ../axwallet_sdk/

flutter_native_splash:
  color: "#ffffff"
  image: ../AXwallet_splash.png
  ios: true
  android: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_logo.png"
  
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/currencies/
    - assets/images/

  fonts:
    - family: MADETommySoft
      fonts:
        - asset: assets/fonts/MADETommySoftRegular.otf
          weight: 400
        - asset: assets/fonts/MADETommySoftMedium.otf
          weight: 500
        - asset: assets/fonts/MADETommySoftBold.otf
          weight: 700
